### ISSUE TITLE
Support - integration test for date time

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#445]

**Comment by Hackeemlunar** [comment]
@kdhrubo Please I want to be assigned this if not already taken.

Plus I need some extra guidelines.

Thanks

**Comment by kdhrubo** [comment]
Sure pls go ahead.

**Comment by kdhrubo** [comment]
This should test various date time and timestamp column data types with operations insert , update delete, read columns , filter using dates etc.

**Comment by kdhrubo** [comment]
@Hackeemlunar your code was good and merged. 

Now to close this issue, you will need to add the tests for other databases also. :)

**Comment by Hackeemlunar** [comment]
Sure, I wanted you to confirm the style and ensure it fits yours.
I will work on the others now.
