### ISSUE TITLE
Add test for default limit

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#662]

**Comment by stephanpio1** [comment]
@kdhrubo Could you assign this issue to me? I need some additional information.

**Comment by kdhrubo** [comment]
1. Once you make first contribution GH allows me to add you to issues. 

2. So by default there is a limit to how many rows a query can fetch..this test is to ensure the parameter is respected.

3. The limit is described here
https://db2rest.com/docs/read/pagination#the-global-limit
