### ISSUE TITLE
Template SQL file support

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#670]
For templatized SQL all templates should be created with Jinjia. 

Jinjia for Java - https://github.com/HubSpot/jinjava

**Acceptance**
Tasks: 
- [ ] Must be able to read from the file system for jar-based deployments.
- [ ] Must be able to load from docker volumes. 
- [ ] Only one folder with multiple SQL files(jinjia format) to be supported.
- [ ] Update documentation on website https://github.com/9tigerio/db2rest-web/issues/7

**Comment by kdhrubo** [comment]
Example SQL File

`SELECT * FROM public.users
WHERE age >= {{ context.params.age }};`

**Comment by thadguidry** [comment]
I think [Pepple](https://pebbletemplates.io/) might be better option as discussed in [Discord thread](https://discord.com/channels/1195238768014274590/1195238768525987974/1277912800760430673)? dunno.

**Comment by kdhrubo** [comment]
Will check.

**Comment by ntananh** [comment]
Just for confirm, the API end-point for this feature is: `api/v1/sql/<filename>`

**Comment by kdhrubo** [comment]
Yes that's correct.
