### ISSUE TITLE
Issue with postgres insert

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#680]
Tested all crud endpoint using timestamps for all databases except Oracle.

One test fails on Postgresql timestamp insertion with incorrect DateTime.
Error Type
DateTime parse error.

Reason.
The processing of postgres data insertion is 'parsed by hand' unlike the others which delegate to the Database itself.
This causes a Date parse error for incorrect Datetime which is not handled in the parsing process. Therefore the server crashes and the error is not propagated and sent to the client.

Proposed Solution.
Make the insertion delegate to the db like all other db supports, so that errors will be caught and properly propagated.

**Comment by Hackeemlunar** [comment]
Performed insertions and other reviews. The issue is rectified.
