### ISSUE TITLE
Replace thymeleaf templates with jte

### ISSUE THREAD

**Issue by grabdoc** [9tigerio/db2rest#705]

**Comment by lserveriiev** [comment]
https://jte.gg/

**Comment by grabdoc** [comment]
Do you want clear separation with Dialects determining the SQL generation templates? Thoughts @lserveriiev ?

**Comment by lserveriiev** [comment]
@grabdoc Yes, I agree with you, the dialects should not define the templates. 

At the same time, I supposed to replace Thymeleaf with jte as a scope of the issue.

**Comment by kdhrubo** [comment]
Ok 👌
