### ISSUE TITLE
Add integration tests for DB metadata API

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#715]

**Comment by Shrman007658** [comment]
Are we talking about the endpoint /v1/rdbms/$dbs API?

**Comment by Shrman007658** [comment]
Also, is there a contributers documentation where we can understand how and where we can set the project up ?

**Comment by kdhrubo** [comment]
> Are we talking about the endpoint /v1/rdbms/$dbs API? 

Yes.
Also there $schema end point

**Comment by kdhrubo** [comment]
> Also, is there a contributers documentation where we can understand how and where we can set the project up ?
> 
None at this moment.
This is a multi module Spring Boot project.
You can fork the repo and load it in IntelliJ or VScode. To run it locally please do follow the instructions in the getting started part of the documentation

**Comment by Shrman007658** [comment]
I am interested in this issue.

**Comment by kdhrubo** [comment]
Go for it. Mark it as work in progress

**Comment by Shrman007658** [comment]
https://github.com/9tigerio/db2rest/pull/728 here is the PR

**Comment by lserveriiev** [comment]
@Shrman007658 I guess it should be integration tests

**Comment by kdhrubo** [comment]
Yes thats correct. Updated the title.
