### ISSUE TITLE
Cant use left join

### ISSUE THREAD

**Issue by farasjibran** [9tigerio/db2rest#819]
Hi, i have the problem with left join when i started to using db2rest. the left join turn into inner join, and i dont know how this even possible. this the screenshoot of the Log in my db2rest

<img width="823" alt="image" src="https://github.com/user-attachments/assets/54824c91-05a6-4c66-b11f-e504daf7beee">

and this the curl i used to generate that Log

```
curl 'http://localhost:8080/v1/rdbms/db/transmigran/_expand' -i -X POST \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '[{"table":"users","type":"LEFT","fields":["nama:updatedBy"],"on":["updated_by==id"]}]'
```

as you can see in the screenshoot, the query its turn to inner join instead of left join

**Comment by thadguidry** [comment]
Hi @farasjibran and welcome to DB2Rest!
Which database and version are you using? PostgreSQL 17.2?

The default join type is an INNER JOIN, so my hunch is that somehow the `"type":"LEFT"` is not getting picked up correctly, possibly due to some other issue in the syntax.
Are you sure you have a field in the `users` table that is called `nama:updatedBy`? not just `updatedBy`?

**Comment by souravroy** [comment]
Thanks @farasjibran for bringing this to our attention, we’re looking into it.

**Comment by farasjibran** [comment]
> Hi @farasjibran and welcome to DB2Rest! Which database and version are you using? PostgreSQL 17.2?
> 
> The default join type is an INNER JOIN, so my hunch is that somehow the `"type":"LEFT"` is not getting picked up correctly, possibly due to some other issue in the syntax. Are you sure you have a field in the `users` table that is called `nama:updatedBy`? not just `updatedBy`? You might try the left join against another field or change the `on` condition, to help us troubleshoot further and try to narrow down the problem and reproduce it. Maybe you could try creating 2 simple tables and performing the left join and see if things work better?

Hi @thadguidry, thanks for the following up this issue. i am using PostgreSQL version 14. and in the table `users` its not have a field name `updatedBy`, the `updatedBy` is the aliases of the `nama` in the table `users`. so i call like `nama:updatedBy`. i have try another table to check if the left join have the problem only in my table `transmigran`. but its return same like the screenshoot i attach in this issues.

I raise this issue because when i use the `type LEFT` in another table, its return same like that. the query show its INNER JOIN not LEFT JOIN. this the screenshoot of comparison of query in db2rest. and in my DBeaver when i test using raw query

db2rest (still same) :

<img width="313" alt="image" src="https://github.com/user-attachments/assets/30140bb5-3483-4c25-b46c-fb87ce300a1a">

this the example of the code :

`
const response = await apiClient.post<Transmigran[]>(
      `${TABLE_TRANSMIGRAN}/_expand?filter=user_id==${id_user}`,
      [
        {
          table: "alamat",
          withTable: "transmigran",
          fields: [
            "info_lokasi_id",
          ],
          on: ["id==transmigran_id"],
        },
        {
          table: "info_lokasi",
          type: "LEFT",
          fields: ["nama_lokasi"],
          on: ["info_lokasi_id==id"],
        },
      ]
    );
`

and this in my DBeaver :

<img width="906" alt="image" src="https://github.com/user-attachments/assets/96c17644-3be6-48e5-9b49-69a276a065a8">

**Comment by farasjibran** [comment]
Found this morning when i check one by one the log that retrieve in db2rest log, and i found some bug in the sintax. you guys **must update** the **documentation** very soon to fix this. i see the type you say in documentation is not the exactly syntax to set the `type` of the join. when i see the log, the syntax to set the `type` of join is `joinType`.

now the query is works like what i want. just please update the documentation, so the people who want to use db2rest will find it easier when using it and not experience things like this again.

i close this issue right now, thanks for the attention guyss.

**Comment by kdhrubo** [comment]
Thanks. Yes we did recently change it. We will update the docs today.

**Comment by thadguidry** [comment]
@farasjibran  You can update the documentation as well, isn't that great?!  Just send a pull request.

**Comment by farasjibran** [comment]
> @farasjibran You can update the documentation as well, isn't that great?! Just send a pull request.

i will send a pull request to update the documentation soon, thankss for the feedback @thadguidry
