### ISSUE TITLE
More integration tests on ISO Date time format

### ISSUE THREAD

**Issue by souravroy** [9tigerio/db2rest#823]

**Comment by souravroy** [comment]
Raised following PR:
https://github.com/9tigerio/db2rest/pull/825

**Comment by thadguidry** [comment]
@souravroy you don't have to manually type the link... instead use the GitHub short keywords syntax in a PR description or commit message (the title or comment) using one of the following formats:
`fixes #823`
`closes #823`
etc.

See details here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue
You can go to your PR and edit the title or the first comment and it will autolink the PR to this Issue.

**Comment by souravroy** [comment]
> @souravroy you don't have to manually type the link... instead use the GitHub short keywords syntax in a PR description or commit message (the title or comment) using one of the following formats: `fixes #823` `closes #823` etc.
> 
> See details here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue You can go to your PR and edit the title or the first comment and it will autolink the PR to this Issue.

Thank you @thadguidry . This's really useful, I'll follow the instructions in my next PR

**Comment by souravroy** [comment]
closed #825
